"use client";

import Link from "next/link";
import { useState } from "react";
import { useAccount, useUpdateAccount } from "@/features/accounts/api";
import { Button, Card, ErrorState, Input, Label, Spinner } from "@/components/ui";
import type { AuthAccount } from "@/lib/types";

export function ProfileOverview({ account }: { account: AuthAccount }) {
  const query = useAccount(account.id); const update = useUpdateAccount(account.id); const profile = query.data?.account ? { ...query.data.account, id: ((query.data.account.distributor as { referralCode?: string } | null)?.referralCode ?? query.data.account.id) } : account;
  const [name, setName] = useState(account.name ?? ""); const [avatarUrl, setAvatarUrl] = useState(account.avatarUrl ?? ""); const [activeSection, setActiveSection] = useState<"business" | "security" | "notifications">("business");
  if (query.isLoading) return <div className="grid place-items-center py-20 text-ink-soft"><Spinner className="h-5 w-5" /></div>;
  if (query.isError || !profile) return <ErrorState message="Could not load your profile." onRetry={() => query.refetch()} />;
  const initials = (name || profile.phone || "D").slice(0, 2).toUpperCase();
  const referralCode = query.data?.account?.distributor?.referralCode ?? "Not available";
  return <div className="profile-overview"><nav className="profile-overview__crumb"><Link href="/dashboard">Dashboard</Link><span>›</span><strong>Profile</strong></nav>
    <Card className="profile-overview__hero profile-overview__hero--accent"><div className="profile-overview__avatar">{avatarUrl ? <img src={avatarUrl} alt="" /> : initials}</div><div className="profile-overview__hero-copy"><div className="profile-overview__name"><h1>{name || "Distributor"}</h1><span>Active</span></div><p>{profile.phone || "Phone not recorded"}</p><div className="profile-overview__progress"><div><small>Profile completion</small><b>85%</b></div><i><em /></i></div></div><Button type="button" onClick={() => document.getElementById("profile-name")?.focus()}>Edit profile</Button></Card>
    <div className="profile-overview__columns"><Card className="profile-overview__personal"><div className="profile-overview__heading"><div><h2>Personal details</h2><p>Update the details shown across your workspace.</p></div></div><form onSubmit={(event) => { event.preventDefault(); update.mutate({ name: name.trim() || undefined, avatarUrl: avatarUrl.trim() || null }); }}><div><Label htmlFor="profile-name">Full name</Label><Input id="profile-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Your name" /></div><div><Label htmlFor="profile-phone">Phone number</Label><Input id="profile-phone" value={profile.phone ?? ""} disabled /></div><div className="profile-overview__upload"><Label htmlFor="profile-avatar">Profile image</Label><div><span>{avatarUrl ? <img src={avatarUrl} alt="" /> : initials}</span><div><strong>Change image</strong><small>SVG, PNG or JPG up to 2MB</small></div></div><Input id="profile-avatar" value={avatarUrl} onChange={(event) => setAvatarUrl(event.target.value)} placeholder="Paste image URL" /></div><Button type="submit" disabled={update.isPending}>{update.isPending ? "Saving…" : "Save changes"}</Button></form></Card>
      <Card className="profile-overview__account profile-overview__account--accent"><div className="profile-overview__heading"><div><h2>Account overview</h2><p>Your distributor account</p></div></div><dl><div><dt><span className="profile-overview__ref-star">★</span> Referral code</dt><dd>{profile.id}</dd></div><div><dt>Joined date</dt><dd>Not available</dd></div><div><dt>Role</dt><dd>Distributor</dd></div><div><dt>Status</dt><dd className="is-active">{profile.status.toLowerCase()}</dd></div></dl><p className="profile-overview__verified">✓ Verified account <small>Protected with secure authentication</small></p></Card></div>
    <div className="profile-overview__links"><Link href="/dashboard/profile/business"><strong>Business details</strong><span>Manage company information</span><b>›</b></Link><Link href="/dashboard/profile/security"><strong>Security &amp; sessions</strong><span>Password and 2FA</span><b>›</b></Link><Link href="/dashboard/profile/notifications"><strong>Notifications</strong><span>Alerts and preferences</span><b>›</b></Link></div>
    <div className="profile-overview__tabs"><button type="button" className={activeSection === "business" ? "is-active" : ""} onClick={() => setActiveSection("business")}>Business details</button><button type="button" className={activeSection === "security" ? "is-active" : ""} onClick={() => setActiveSection("security")}>Security &amp; sessions</button><button type="button" className={activeSection === "notifications" ? "is-active" : ""} onClick={() => setActiveSection("notifications")}>Notifications</button></div><Card className="profile-overview__section"><h2>{activeSection === "business" ? "Business details" : activeSection === "security" ? "Security & sessions" : "Notifications"}</h2><p>{activeSection === "business" ? "Manage the company information associated with your distributor account." : activeSection === "security" ? "Review authentication and active sessions for your account." : "Choose which order, payment, and inventory alerts you receive."}</p><div className="profile-overview__section-grid">{(activeSection === "business" ? ["Business name", "Territory", "GST / tax details", "Business address"] : activeSection === "security" ? ["Password and two-factor authentication", "Active sessions", "Sign out of other devices"] : ["Order updates", "Payment reminders", "Low-stock alerts", "Email and push preferences"]).map((item) => <div key={item}><span>{item}</span><b>›</b></div>)}</div></Card>
  </div>;
}
